apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    app: {{.Values.service.app}}
  ports:
  - name: http
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
  type: {{.Values.service.type}}