apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: disk-azure
    namespace: devops-tools
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi